// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs2_WOF1JM-qPeNRExdQZ4dYS7QgzAzeQ',
    appId: '1:869560208511:web:61ffc8f60eacff9784c34a',
    messagingSenderId: '869560208511',
    projectId: 'todoapp-eece1',
    authDomain: 'todoapp-eece1.firebaseapp.com',
    storageBucket: 'todoapp-eece1.appspot.com',
    measurementId: 'G-Q18VQL59KE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4M6BGqJT6M3hGltrhWo6PyRBI439n18U',
    appId: '1:869560208511:android:f992eb0537244fb384c34a',
    messagingSenderId: '869560208511',
    projectId: 'todoapp-eece1',
    storageBucket: 'todoapp-eece1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuPQyk276pPDFeR3omACLqem224mjkeTw',
    appId: '1:869560208511:ios:61a4f91feb640ff184c34a',
    messagingSenderId: '869560208511',
    projectId: 'todoapp-eece1',
    storageBucket: 'todoapp-eece1.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuPQyk276pPDFeR3omACLqem224mjkeTw',
    appId: '1:869560208511:ios:61a4f91feb640ff184c34a',
    messagingSenderId: '869560208511',
    projectId: 'todoapp-eece1',
    storageBucket: 'todoapp-eece1.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs2_WOF1JM-qPeNRExdQZ4dYS7QgzAzeQ',
    appId: '1:869560208511:web:3b682699c43fdb5a84c34a',
    messagingSenderId: '869560208511',
    projectId: 'todoapp-eece1',
    authDomain: 'todoapp-eece1.firebaseapp.com',
    storageBucket: 'todoapp-eece1.appspot.com',
    measurementId: 'G-5L25QL70TP',
  );
}
